x_batch_size: 64
z_batch_size: 64
z_dims: 100
z_std: 1
num_epochs: 100 
prior_std: 1
step_size: 0.0005
prior: normal
summary_savedir: summary
summary_n: 20
exp: unsupervised
n_supervised: 100
n_g: 5
n_d: 1
test_batch_size: 512
output_dir: './semi-search'
arch: MLP
supervised_scaling: 1
