x_batch_size: 64
z_batch_size: 64
z_dims: 100
z_std: 1
num_epochs: 100 
prior_std: 1
step_size: 0.0001
prior: normal
opt: GradientDescent
summary_savedir: summary
summary_n: 20
exp: semisupervised
summary: False 
n_supervised: 2000
n_g: 10
n_d: 1
test_batch_size: 256
output_dir: './semi-search-15'
arch: dcgan
supervised_scaling: 1
