x_batch_size: 64
z_batch_size: 64
z_dims: 100
z_std: 1
num_epochs: 100 
prior_std: 1
step_size: 0.005
opt: Adagrad
prior: normal
summary_savedir: summary
summary: False 
summary_n: 20
exp: semisupervised
n_supervised: 2000
n_g: 5
n_d: 1
test_batch_size: 256
output_dir: './semi-search'
arch: dcgan
supervised_scaling: 1
