z_batch_size: 200
summary_n: 20
test_batch_size: 200
num_epochs: 100
summary_savedir: summary
output_dir: ./ss-mnist-exp
x_batch_size: 200
n_g: 10
step_size: 0.001
z_dims: 100
prior: normal
n_supervised: 100
prior_std: 5
z_std: 1
exp: semisupervised
n_d: 1
